In [68]:
import caffe
import numpy as np
import cv2
import matplotlib.pyplot as plt
import glob
import os
%matplotlib inline

In [69]:
#net = caffe.Net('xiaojing_dilated_convolution/no_pad_dia/11/deploy_denoise.prototxt',
#                'xiaojing_dilated_convolution/no_pad_dia/new_set/11/denoising_net_iter_1500000.caffemodel', 
#                caffe.TEST )

In [70]:
#transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
#transformer.set_mean('data',104)

In [71]:
#net.blobs['data'].reshape(1,1,400,275)

In [72]:
val_images_path = '/home/rgsl888/Finger_Print_dataset/validation_out_xiaojing_dia_with_pad_1200000//'
val_out_path = '/home/rgsl888/Finger_Print_dataset/validation_out_xiaojing_dia_with_pad_conv/'
img_ext = '.jpg'

if not os.path.exists(val_images_path):
    os.makedirs(val_images_path)
if not os.path.exists(val_out_path):
    os.makedirs(val_out_path)
images = glob.glob (val_images_path + "/*" + img_ext)


In [73]:
for img in images:
    im = cv2.imread(img,0)
    #im = im - np.array((104.00698793)) 
    #net.blobs['data'].data[...] = transformer.preprocess('data', im)
    #out = net.forward()
    #plt.imshow(out['output'][0][0])
    img_name = img.split('/')
    #denoised_img = out['output'][0][0]
    #denoised_img += np.array((104.00698793))
    #denoised_img = np.clip(np.rint(denoised_img), 0, 255.0)
    #denoised_img = cv2.resize(denoised_img, (275, 400))
    im[:,0] = 255;
    im[:,1] = 255;
    im[:,2] = 255;
    im[:,3] = 255;
    im[:,4] = 255;
   # im[:,5] = 255;
   # im[:,6] = 255;
    im[:,-1] = 255;
    im[:,-2] = 255;
    im[:,-3] = 255;
    im[:,-4] = 255;
   # im[:,-5] = 255;
   # im[:,-6] = 255;
    im[-1,:] = 255;
    im[-2,:] = 255;
    im[-3,:] = 255;
    im[-4,:] = 255;
   # im[-5,:] = 255;
   # im[-6,:] = 255;
    im[0,:] = 255;
    im[1,:] = 255;
    im[2,:] = 255;
    im[3,:] = 255;
    im[4,:] = 255;
   # im[5,:] = 255;
   # im[6,:] = 255;
    
    cv2.imwrite(val_out_path + img_name[-1], im)

In [49]:
import numpy as np

b = [[1,1,1,1], [1,1,1,1], [1,1,1,1], [1,1,1,1]]
a = np.array(b)
a [-2,:] = 5

print (a)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [34]:
print (a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


[[5 5 5 5]
 [5 5 5 5]
 [1 1 1 1]
 [1 1 1 1]]
